def __main__():
    '''Find number of distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100.'''
    numbers = set()
    for x in range(2,101):
        for y in range(2,101):
            numbers.add(x**y)
    print(len(numbers))

if __name__ == '__main__':
    __main__()
